general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10
offset = { x = 0, y = 2 }
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Propo"
style = "Regular"

[ font.bold ]
family = "JetBrainsMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Propo"
style = "Italic"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
opacity = 1

# Colors (Gruvbox Material Dark Medium)
[colors.primary]
background = "0x32302f"
foreground = "0xdfbf8e"

[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe3a84e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]
